# --- !Ups
ALTER TABLE User ADD COLUMN Password TEXT NOT NULL DEFAULT '';
ALTER TABLE User ADD COLUMN DateCreated TEXT NOT NULL DEFAULT '';

# --- !Downs
ALTER TABLE User DRPO COLUMN Password;
ALTER TABLE User DRPO COLUMN DateCreated;
