# --- !Ups
ALTER TABLE User ADD COLUMN Password TEXT NOT NULL DEFAULT '';
ALTER TABLE User ADD COLUMN DateCreated TEXT NOT NULL DEFAULT '';
ALTER TABLE User ADD COLUMN Hostname TEXT NOT NULL DEFAULT '';
ALTER TABLE User ADD COLUMN LastIdentified TEXT NOT NULL DEFAULT '';

# --- !Downs
ALTER TABLE User DROP COLUMN Password;
ALTER TABLE User DROP COLUMN DateCreated;
ALTER TABLE User DROP COLUMN Hostname;
ALTER TABLE User DROP COLUMN LastIdentified;
