# --- !Ups
CREATE TABLE Network (
  NetworkId INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL UNIQUE
);

CREATE TABLE Channel (
  ChannelId INTEGER PRIMARY KEY AUTOINCREMENT,
  Network INTEGER NOT NULL,
  Name TEXT NOT NULL,
  Autojoin BOOLEAN NOT NULL DEFAULT 1,

  UNIQUE(Network, Name),
  FOREIGN KEY(Network) REFERENCES Network(NetworkId)
);

# --- !Downs
DROP TABLE Channel;
